Merged changes from the final CVS revision.
This also includes minor changes to the build system so that the
standard build system and HPC-GAP's can exist side by side.

diff --git a/extern/Makefile.in b/extern/Makefile.in
--- a/extern/Makefile.in
+++ b/extern/Makefile.in
@@ -1,34 +1,69 @@
-CFLAGS=@CFLAGS@ $(COPTS)
+ifndef ABI
+ ABI=@ABI@
+endif
+CFLAGS=@CFLAGS@ @ABI_CFLAGS@ $(COPTS)
 LDFLAGS=@LDFLAGS@ $(LOPTS)
 CC=@CC@
-GMPVER=4.2.2
+GAPARCH=@GAPARCH@
 MPFRVER=2.3.1
 
-all: jenkins
+all: $(MAKE_GMP)
 
-all_gmp: jenkins gmp
+all_gmp_mpfr: $(MAKE_GMP) mpfr
 
-all_gmp_mpfr: jenkins gmp mpfr
+../../../extern/gmp-5.0.4: ../../../extern/gmp-5.0.4.tar.gz
+	( cd ../../../extern; tar zxvf gmp-5.0.4.tar.gz )
 
-jenkins: jenkins/jhash.o ../../../extern/include/jhash.h
+../../../extern/gmp-5.0.5: ../../../extern/gmp-5.0.5.tar.gz
+	( cd ../../../extern; tar zxvf gmp-5.0.5.tar.gz )
 
-jenkins/jhash.o: ../../../extern/jenkins/jhash.o 
-	mkdir -p jenkins
-	ln -sf ../$^ $@
+gmp_config: ../../../extern/gmp-$(GMP_VER)
+	@mkdir -p gmp-$(GMP_VER)
+	@( cd ../../../extern/gmp-$(GMP_VER); \
+	   gmp_conf=no; \
+	   if test -r Makefile; then \
+	    if ! test -r LASTBUILD.$(GAPARCH); then \
+	     make distclean; \
+	     gmp_conf=yes; \
+	    fi; \
+	   else \
+	    gmp_conf=yes; \
+	   fi; \
+	   if test "$$gmp_conf" = "yes"; then \
+	    echo ""; \
+	    echo "Configuring GMP. Logging to bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
+	    echo ""; \
+	    ./configure --prefix=`pwd`/../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER) ABI=$(ABI) \
+	     > ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log 2>&1; \
+	    rm -f LASTBUILD*; \
+	    touch LASTBUILD.$(GAPARCH); \
+	   fi; )
 
-../../../extern/include/jhash.h: ../../../extern/jenkins/jhash.h
-	( cd ../../../extern/include; ln -sf ../jenkins/jhash.h .; )
+gmp_build: gmp_config
+	@( cd ../../../extern/gmp-$(GMP_VER); \
+	   echo "" ;\
+	    echo "Building GMP. Logging to bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
+	   echo "" ;\
+	    $(MAKE) >> ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log 2>&1 ; \
+	   if ! test -r ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/MAKE_CHECK_PASSED; then \
+	    ( echo "" ;\
+	      echo "Checking GMP. Logging to bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
+	      echo "" ; \
+	      $(MAKE) check >> ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log 2>&1 ; \
+	      if ! [ $$? -eq 0 ] ; then \
+	       ( echo "" ;\
+	         echo "***Error: GMP self-check has failed. See bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log for details.***"; \
+	         echo "" ;\
+		 exit 1 ); \
+	      else \
+	       touch ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/MAKE_CHECK_PASSED; \
+	      fi; ) \
+	   fi )
 
-../../../extern/jenkins/jhash.o:  ../../../extern/jenkins/jhash.h ../../../extern/jenkins/jhash.c
-	(cd ../../../extern/jenkins; $(MAKE) CC='$(CC)' CFLAGS='$(CFLAGS)' LDFLAGS='$(LDFLAGS)') 
-
-gmp:    
-	if ! test -d ../../../extern/gmp-$(GMPVER); then \
-		( cd ../../../extern; tar zxvf gmp-$(GMPVER).tar.gz ); fi
-	if ! test -r ../../../extern/gmp-$(GMPVER)/Makefile ; then \
-		( cd ../../../extern/gmp-$(GMPVER); \
-		  ./configure --prefix=`pwd`/.. ); fi
-	( cd ../../../extern/gmp-$(GMPVER); $(MAKE); )
-	( cd ../../../extern/include; ln -sf ../gmp-$(GMPVER)/gmp.h )
-	( cd ../../../extern/lib; for i in libgmp.a libgmp.la libgmp.so*; do \
-	  ln -sf ../gmp-$(GMPVER)/.libs/$$i .; done )
+gmp: gmp_build 
+	@( cd ../../../extern/gmp-$(GMP_VER); \
+	    echo ""; \
+	    echo "Installing GMP in bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/. Logging to bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
+	    echo ""; \
+	    $(MAKE) install >> ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log 2>&1 )
+	@( rm -f gmp; ln -s gmp-$(GMP_VER) gmp )
