Commit v4.5.3

diff --git a/extern/Makefile.in b/extern/Makefile.in
--- a/extern/Makefile.in
+++ b/extern/Makefile.in
@@ -4,24 +4,25 @@ endif
 CFLAGS=@CFLAGS@ @ABI_CFLAGS@ $(COPTS)
 LDFLAGS=@LDFLAGS@ $(LOPTS)
 CC=@CC@
+GAPARCH=@GAPARCH@
 MPFRVER=2.3.1
 
 all: $(MAKE_GMP)
 
 all_gmp_mpfr: $(MAKE_GMP) mpfr
 
-../../../extern/gmp-5.0.1: ../../../extern/gmp-5.0.1-patched.tar.gz
-	( cd ../../../extern; tar zxvf gmp-5.0.1-patched.tar.gz )
+../../../extern/gmp-5.0.2: ../../../extern/gmp-5.0.2-patched.tar.gz
+	( cd ../../../extern; tar zxvf gmp-5.0.2-patched.tar.gz )
 
-../../../extern/gmp-5.0.2: ../../../extern/gmp-5.0.2.tar.gz
-	( cd ../../../extern; tar zxvf gmp-5.0.2.tar.gz )
+../../../extern/gmp-5.0.4: ../../../extern/gmp-5.0.4.tar.gz
+	( cd ../../../extern; tar zxvf gmp-5.0.4.tar.gz )
 
 gmp_config: ../../../extern/gmp-$(GMP_VER)
 	@mkdir -p gmp-$(GMP_VER)
 	@( cd ../../../extern/gmp-$(GMP_VER); \
 	   gmp_conf=no; \
 	   if test -r Makefile; then \
-	    if ! test -r LASTBUILD.$(TARGET)-$(BASECC)-$(CONFIGNAME); then \
+	    if ! test -r LASTBUILD.$(GAPARCH); then \
 	     make distclean; \
 	     gmp_conf=yes; \
 	    fi; \
@@ -30,39 +31,39 @@ gmp_config: ../../../extern/gmp-$(GMP_VER)
 	   fi; \
 	   if test "$$gmp_conf" = "yes"; then \
 	    echo ""; \
-	    echo "Configuring GMP. Logging to bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
+	    echo "Configuring GMP. Logging to bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
 	    echo ""; \
-	    ./configure --prefix=`pwd`/../../bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER) ABI=$(ABI) \
-	     > ../../bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log 2>&1; \
+	    ./configure --prefix=`pwd`/../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER) ABI=$(ABI) \
+	     > ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log 2>&1; \
 	    rm -f LASTBUILD*; \
-	    touch LASTBUILD.$(TARGET)-$(BASECC)-$(CONFIGNAME); \
+	    touch LASTBUILD.$(GAPARCH); \
 	   fi; )
 
 gmp_build: gmp_config
 	@( cd ../../../extern/gmp-$(GMP_VER); \
 	   echo "" ;\
-	    echo "Building GMP. Logging to bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
+	    echo "Building GMP. Logging to bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
 	   echo "" ;\
-	    $(MAKE) >> ../../bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log 2>&1 ; \
-	   if ! test -r ../../bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/MAKE_CHECK_PASSED; then \
+	    $(MAKE) >> ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log 2>&1 ; \
+	   if ! test -r ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/MAKE_CHECK_PASSED; then \
 	    ( echo "" ;\
-	      echo "Checking GMP. Logging to bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
+	      echo "Checking GMP. Logging to bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
 	      echo "" ; \
-	      $(MAKE) check >> ../../bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log 2>&1 ; \
+	      $(MAKE) check >> ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log 2>&1 ; \
 	      if ! [ $$? -eq 0 ] ; then \
 	       ( echo "" ;\
-	         echo "***Error: GMP self-check has failed. See bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log for details.***"; \
+	         echo "***Error: GMP self-check has failed. See bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log for details.***"; \
 	         echo "" ;\
 		 exit 1 ); \
 	      else \
-	       touch ../../bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/MAKE_CHECK_PASSED; \
+	       touch ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/MAKE_CHECK_PASSED; \
 	      fi; ) \
 	   fi )
 
 gmp: gmp_build 
 	@( cd ../../../extern/gmp-$(GMP_VER); \
 	    echo ""; \
-	    echo "Installing GMP in bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/. Logging to bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
+	    echo "Installing GMP in bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/. Logging to bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log. Please wait... "; \
 	    echo ""; \
-	    $(MAKE) install >> ../../bin/$(TARGET)-$(BASECC)-$(CONFIGNAME)/extern/gmp-$(GMP_VER)/build_log 2>&1 )
+	    $(MAKE) install >> ../../bin/$(GAPARCH)/extern/gmp-$(GMP_VER)/build_log 2>&1 )
 	@( rm -f gmp; ln -s gmp-$(GMP_VER) gmp )
