Initial checkin.

diff --git a/dev/DistributionUpdate/rsyncserv/gapsync/gapsync b/dev/DistributionUpdate/rsyncserv/gapsync/gapsync
--- a/dev/DistributionUpdate/rsyncserv/gapsync/gapsync
+++ b/dev/DistributionUpdate/rsyncserv/gapsync/gapsync
@@ -1,7 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 
 ##  init and syncronization script for GAP 4.4 under Linux
-##  $Id$     Frank Lübeck
+##  $Id: gapsync,v 1.15 2008/04/17 08:46:44 gap Exp $     Frank Lübeck
+arch=`uname -m`
 if [ ! -f gapsync.issyncdir ]; then
   echo Welcome to the GAP installation by syncronizing a reference installation.
   echo 
@@ -15,12 +16,15 @@ if [ ! -f gapsync.issyncdir ]; then
     echo "       ... hm, found: "$a
   fi
 
-  echo "          on i686 compatible architecture"
-  a=`uname -m`
-  if [ $a'X' == i686X ]; then
-    echo "       ... looks ok"
+  echo "          on i686 and x86_64 compatible architecture"
+  if [ $arch'X' == i686X ]; then
+    echo "       ... looks ok (i686)"
   else
-    echo "       ... hm, found: "$a
+    if [ $arch'X' == x86_64X ]; then
+      echo "       ... looks ok (x86_64)"
+    else
+      echo "       ... hm, found: "$a
+    fi
   fi
 
   echo "          the 'rsync' utility program"
@@ -32,13 +36,13 @@ if [ ! -f gapsync.issyncdir ]; then
     exit 1
   fi
 
-  echo "          a directory with about 500 MB of free space"
+  echo "          a directory with at least 750 MB of free space"
   echo
   echo
 
-  echo "Please, tell me a path for the installation of GAP (default /usr/local/lib)"
-  echo "Everything will be stored in a subdirectory 'gap4r4', except for the start"
-  echo "scripts."
+  echo "Please, tell me an absolute path for the installation of GAP "
+  echo "(default is /usr/local/lib).  Everything will be stored in a "
+  echo "subdirectory 'gap4r4', except for the start scripts."
   read -p '---> ' -e gappath
   if [ $gappath'X' == 'X' ]; then
     gappath="/usr/local/lib/gap4r4"
@@ -46,11 +50,44 @@ if [ ! -f gapsync.issyncdir ]; then
     gappath=$gappath'/gap4r4'
   fi
 
-  echo "Also, tell me a path for the scripts to start GAP (default /usr/local/bin)"
+  echo "Also, tell me an absolute path for the scripts to start GAP "
+  echo "(default is /usr/local/bin)"
   echo ""
   read -p '---> ' -e binpath
   if [ $binpath'X' == 'X' ]; then
     binpath="/usr/local/bin"
+  fi
+  
+  # check if some scripts to install would overwrite something
+  exist=""
+  for nam in gap xgap gapL gapsync pargap gac; do
+    if [ -f $binpath/$nam ]; then
+      exist=$exist" "$nam
+    fi
+  done
+  if [ $arch'X' == x86_64X ]; then
+    for nam in gap64 gap64L pargap64 gac64; do
+      if [ -f $binpath/$nam ]; then
+        exist=$exist" "$nam
+      fi
+    done
+  fi
+  if [ "$exist"'X' != 'X' ]; then
+    echo ""
+    echo "There are already the following scripts in "$binpath":"
+    echo "                "$exist
+    echo "If you don't want me to delete them now, say 'No' here and move"
+    echo "them away before starting me again."
+    echo "Shall I delete "$exist
+    echo "            in "$binpath" now? (y/N)"
+    read -n 1 del
+    echo
+    if [ $del'X' != 'yX' ]; then
+      echo Ok, start me again after moving them away.
+      exit 3
+    else
+      rm -f $binpath/{gap,xgap,gapL,gapsync,pargap,gac,gap64,gap64L,pargap64,gac64}
+    fi
   fi
   
   echo "Going to syncronize GAP in: "$gappath
@@ -86,7 +123,7 @@ else
   cd $gappath
 fi
 
-line=''$rsync' -avz --delete --port 8731 --exclude=local/ --exclude=pkg/atlasrep/datagens/ --exclude=pkg/atlasrep/dataword/ beteigeuze.math.rwth-aachen.de::gap4r4/ .'
+line=''$rsync' -avz --delete --port 8731 --exclude=local/ beteigeuze.math.rwth-aachen.de::gap4r4/ .'
 echo 'Calling: '$line 
 
 if ! $line; then
@@ -108,7 +145,24 @@ else
   echo "       local/bin/CreateWorkspace and editing this copy.)"
   gapsync/CreateWorkspace.sh
 fi
-
+if [ $arch'X' = x86_64X ]; then
+  echo "Also creating new workspace for 64-bit version ..."
+  if [ -f local/bin/CreateWorkspace64 ]; then
+    echo "Using local/bin/CreateWorkspace64 ..."
+    local/bin/CreateWorkspace64
+  elif [ -f local/bin/CreateWorkspace ]; then
+    echo "Using local/bin/CreateWorkspace ..."
+    local/bin/CreateWorkspace
+  else
+    echo "Using gapsync/CreateWorkspace.sh x86_64 ..."
+    echo "      (You can customize this by copying gapsync/CreateWorkspace.sh to"
+    echo "       local/bin/CreateWorkspace64 or local/bin/CreateWorkspace"
+    echo "       and editing this copy.)"
+    gapsync/CreateWorkspace.sh x86_64
+  fi
+fi
+  
+mkdir -p $binpath
 if [ ! -f $binpath/gap ]; then
   rm -f local/bin/gap
   echo "Creating start script "$binpath"/gap," 
@@ -117,7 +171,29 @@ if [ ! -f $binpath/gap ]; then
   echo "GAP_DIR="$gappath >> local/bin/gap
   cat gapsync/gap.sh >> local/bin/gap
   chmod 755 local/bin/gap
-
+  ln -s $gappath/local/bin/gap $binpath
+fi
+if [ ! -f $binpath/xgap ]; then
+  rm -f local/bin/xgap
+  echo "Creating start script "$binpath"/xgap," 
+  echo "      (you can customize this by editing local/bin/xgap)."
+  echo "#!/bin/sh" > local/bin/xgap
+  echo "GAP_DIR="$gappath >> local/bin/xgap
+  cat gapsync/xgap.sh >> local/bin/xgap
+  chmod 755 local/bin/xgap
+  ln -s $gappath/local/bin/xgap $binpath
+fi
+if [ ! -f $binpath/pargap ]; then
+  rm -f local/bin/pargap
+  echo "Creating start script "$binpath"/pargap," 
+  echo "      (you can customize this by editing local/bin/pargap)."
+  echo "#!/bin/sh" > local/bin/pargap
+  echo "GAP_DIR="$gappath >> local/bin/pargap
+  cat gapsync/pargap.sh >> local/bin/pargap
+  chmod 755 local/bin/pargap
+  ln -s $gappath/local/bin/pargap $binpath
+fi
+if [ ! -f $binpath/gapL ]; then
   rm -f local/bin/gapL
   echo "Creating start script "$binpath"/gapL," 
   echo "      (you can customize this by editing local/bin/gapL)."
@@ -126,24 +202,52 @@ if [ ! -f $binpath/gap ]; then
   echo "BINPATH="$binpath >> local/bin/gapL
   cat gapsync/gapL >> local/bin/gapL
   chmod 755 local/bin/gapL
-  
+  ln -s $gappath/local/bin/gapL $binpath
+fi
+if [ ! -f $binpath/gapsync ]; then
   rm -f local/bin/gapsync
   echo "Adjusting update script "$binpath"/gapsync," 
   echo "#!/bin/sh" > local/bin/gapsync
   echo "cd "$gappath"/gapsync" >> local/bin/gapsync
   cat gapsync/gapsync >> local/bin/gapsync
   chmod 755 local/bin/gapsync
- 
-  rm -f $binpath/{gap,gapL,gapsync,gac}
-  ln -s $gappath/local/bin/gap $binpath
-  ln -s $gappath/local/bin/gapL $binpath
   ln -s $gappath/local/bin/gapsync $binpath
-  ln -s $gappath/local/bin/i686-pc-linux-gnu-gcc/gac $binpath
-  if [ ! -f $binpath/gap ]; then
-    echo "Error: Could not create link "$binpath"/gap"
-    exit 6
+fi
+if [ ! -f $binpath/gap ]; then
+  echo "Error: Could not create link "$binpath"/gap"
+  exit 6
+fi
+if [ $arch'X' = x86_64X ]; then
+  if [ ! -f $binpath/gap64 ]; then
+    rm -f local/bin/gap64
+    echo "Creating start script "$binpath"/gap64," 
+    echo "      (you can customize this by editing local/bin/gap)."
+    echo "#!/bin/sh" > local/bin/gap64
+    echo "GAP_DIR="$gappath >> local/bin/gap64
+    cat gapsync/gap64.sh >> local/bin/gap64
+    chmod 755 local/bin/gap64
+    ln -s $gappath/local/bin/gap64 $binpath
+  fi
+  if [ ! -f $binpath/pargap64 ]; then
+    rm -f local/bin/pargap64
+    echo "Creating start script "$binpath"/pargap64," 
+    echo "      (you can customize this by editing local/bin/pargap)."
+    echo "#!/bin/sh" > local/bin/pargap
+    echo "GAP_DIR="$gappath >> local/bin/pargap64
+    cat gapsync/pargap64.sh >> local/bin/pargap64
+    chmod 755 local/bin/pargap64
+    ln -s $gappath/local/bin/pargap64 $binpath
+  fi
+  if [ ! -f $binpath/gap64L ]; then
+    rm -f local/bin/gap64L
+    echo "Creating start script "$binpath"/gap64L," 
+    echo "      (you can customize this by editing local/bin/gapL)."
+    echo "#!/bin/sh" > local/bin/gap64L
+    echo "GAP_DIR="$gappath >> local/bin/gap64L
+    echo "BINPATH="$binpath >> local/bin/gap64L
+    cat gapsync/gap64L >> local/bin/gap64L
+    chmod 755 local/bin/gap64L
+    ln -s $gappath/local/bin/gap64L $binpath
   fi
 fi
-
-
 
